# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\rpython_bridge\"U\n\x0cTradeMessage\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\x0c\n\x04side\x18\x05 \x01(\t\"\'\n\x08\x44omLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0c\n\x04size\x18\x02 \x01(\x03\"v\n\nDomMessage\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\t\x12%\n\x04\x62ids\x18\x03 \x03(\x0b\x32\x17.python_bridge.DomLevel\x12%\n\x04\x61sks\x18\x04 \x03(\x0b\x32\x17.python_bridge.DomLevelB\x1e\xaa\x02\x1bPythonBridgeQuantower.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033PythonBridgeQuantower.Proto'
  _globals['_TRADEMESSAGE']._serialized_start=33
  _globals['_TRADEMESSAGE']._serialized_end=118
  _globals['_DOMLEVEL']._serialized_start=120
  _globals['_DOMLEVEL']._serialized_end=159
  _globals['_DOMMESSAGE']._serialized_start=161
  _globals['_DOMMESSAGE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
