<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <QT_Path>C:\Quantower\TradingPlatform\v1.145.17</QT_Path>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AlgoType>Strategy</AlgoType>
    <AssemblyName>PythonBridgeQuantower</AssemblyName>
    <RootNamespace>PythonBridgeQuantower</RootNamespace>
    <StartAction>Program</StartAction>
    <StartProgram>$(QT_Path)\Console.StarterNew.exe</StartProgram>
    <StartArguments>--address 127.0.0.1 --port 52879</StartArguments>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>$(QT_Path)\bin\TradingPlatform.BusinessLayer.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
